package com.adk.db.pingpong;
// Generated Dec 24, 2016 8:57:25 AM by Hibernate Tools 4.3.5.Final

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Authorities generated by hbm2java
 */
@XmlRootElement
public class Authorities implements java.io.Serializable {

	private AuthoritiesId id;
	private Users users;

	public Authorities() {
	}

	public Authorities(AuthoritiesId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public AuthoritiesId getId() {
		return this.id;
	}

	public void setId(AuthoritiesId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
