package com.adk.db.pingpong;

import java.util.HashSet;
import java.util.Set;
// Generated Dec 5, 2016 3:59:42 PM by Hibernate Tools 4.3.1.Final

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Category generated by hbm2java
 */
@XmlRootElement(name="category")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlSeeAlso({Event.class})
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private String gender;
	private String matchType;
	@XmlElement(name="events")
	private Set events = new HashSet(0);

	public Category() {
	}

	public Category(String gender, String matchType) {
		this.gender = gender;
		this.matchType = matchType;
	}

	public Category(String categoryName, String gender, String matchType, Set events) {
		this.categoryName = categoryName;
		this.gender = gender;
		this.matchType = matchType;
		this.events = events;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMatchType() {
		return this.matchType;
	}

	public void setMatchType(String matchType) {
		this.matchType = matchType;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

}
