package com.adk.db.pingpong;
// Generated Dec 5, 2016 3:59:42 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Category generated by hbm2java
 */
@XmlRootElement
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private String gender;
	
	private Set tournaments = new HashSet(0);

	public Category() {
	}

	public Category(String categoryName, String gender, Set tournaments) {
		this.categoryName = categoryName;
		this.gender = gender;
		this.tournaments = tournaments;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Set getTournaments() {
		return this.tournaments;
	}

	public void setTournaments(Set tournaments) {
		this.tournaments = tournaments;
	}

}
