package com.adk.db.pingpong;
// Generated Dec 5, 2016 11:55:23 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;


/**
 * GroupMatchesDetails generated by hbm2java
 */
@XmlRootElement(name="Groups")
@XmlAccessorType(XmlAccessType.FIELD)
public class GroupMatchesDetails implements java.io.Serializable {

	private Integer groupId;
	
	@XmlTransient
	private Tournament tournament;
	
	private String groupName;
	private int matchId;
	private Date matchDate;
	private int player1Id;
	private int player2Id;
	private Integer player1Score;
	private Integer player2Score;
	private String winner;
	private Set gameScores = new HashSet(0);

	public GroupMatchesDetails() {
	}

	public GroupMatchesDetails(Tournament tournament, int matchId, Date matchDate, int player1Id, int player2Id) {
		this.tournament = tournament;
		this.matchId = matchId;
		this.matchDate = matchDate;
		this.player1Id = player1Id;
		this.player2Id = player2Id;
	}

	public GroupMatchesDetails(Tournament tournament, String groupName, int matchId, Date matchDate, int player1Id,
			int player2Id, Integer player1Score, Integer player2Score, String winner, Set gameScores) {
		this.tournament = tournament;
		this.groupName = groupName;
		this.matchId = matchId;
		this.matchDate = matchDate;
		this.player1Id = player1Id;
		this.player2Id = player2Id;
		this.player1Score = player1Score;
		this.player2Score = player2Score;
		this.winner = winner;
		this.gameScores = gameScores;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Tournament getTournament() {
		return this.tournament;
	}

	public void setTournament(Tournament tournament) {
		this.tournament = tournament;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public int getMatchId() {
		return this.matchId;
	}

	public void setMatchId(int matchId) {
		this.matchId = matchId;
	}

	public Date getMatchDate() {
		return this.matchDate;
	}

	public void setMatchDate(Date matchDate) {
		this.matchDate = matchDate;
	}

	public int getPlayer1Id() {
		return this.player1Id;
	}

	public void setPlayer1Id(int player1Id) {
		this.player1Id = player1Id;
	}

	public int getPlayer2Id() {
		return this.player2Id;
	}

	public void setPlayer2Id(int player2Id) {
		this.player2Id = player2Id;
	}

	public Integer getPlayer1Score() {
		return this.player1Score;
	}

	public void setPlayer1Score(Integer player1Score) {
		this.player1Score = player1Score;
	}

	public Integer getPlayer2Score() {
		return this.player2Score;
	}

	public void setPlayer2Score(Integer player2Score) {
		this.player2Score = player2Score;
	}

	public String getWinner() {
		return this.winner;
	}

	public void setWinner(String winner) {
		this.winner = winner;
	}

	public Set getGameScores() {
		return this.gameScores;
	}

	public void setGameScores(Set gameScores) {
		this.gameScores = gameScores;
	}

}
