package com.adk.db.pingpong;
// Generated Dec 1, 2016 12:08:39 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MatchScoreDetails generated by hbm2java
 */
public class MatchScoreDetails implements java.io.Serializable {

	private Integer matchId;
	private Date matchDate;
	private int player1Id;
	private int player2Id;
	private String result1;
	private Set playerScoreDetailses = new HashSet(0);

	public MatchScoreDetails() {
	}

	public MatchScoreDetails(Date matchDate, int player1Id, int player2Id, String result1) {
		this.matchDate = matchDate;
		this.player1Id = player1Id;
		this.player2Id = player2Id;
		this.result1 = result1;
	}

	public MatchScoreDetails(Date matchDate, int player1Id, int player2Id, String result1, Set playerScoreDetailses) {
		this.matchDate = matchDate;
		this.player1Id = player1Id;
		this.player2Id = player2Id;
		this.result1 = result1;
		this.playerScoreDetailses = playerScoreDetailses;
	}

	public Integer getMatchId() {
		return this.matchId;
	}

	public void setMatchId(Integer matchId) {
		this.matchId = matchId;
	}

	public Date getMatchDate() {
		return this.matchDate;
	}

	public void setMatchDate(Date matchDate) {
		this.matchDate = matchDate;
	}

	public int getPlayer1Id() {
		return this.player1Id;
	}

	public void setPlayer1Id(int player1Id) {
		this.player1Id = player1Id;
	}

	public int getPlayer2Id() {
		return this.player2Id;
	}

	public void setPlayer2Id(int player2Id) {
		this.player2Id = player2Id;
	}

	public String getResult1() {
		return this.result1;
	}

	public void setResult1(String result1) {
		this.result1 = result1;
	}

	public Set getPlayerScoreDetailses() {
		return this.playerScoreDetailses;
	}

	public void setPlayerScoreDetailses(Set playerScoreDetailses) {
		this.playerScoreDetailses = playerScoreDetailses;
	}

}
