package com.adk.db.pingpong;
// Generated Dec 1, 2016 12:08:39 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * PlayerScoreDetails generated by hbm2java
 */
public class PlayerScoreDetails implements java.io.Serializable {

	private Integer rowId;
	private MatchScoreDetails matchScoreDetails;
	private PlayerDetails playerDetails;
	private Date matchDate;
	private int score;
	private int bonus;
	private int totalScore;

	public PlayerScoreDetails() {
	}

	public PlayerScoreDetails(MatchScoreDetails matchScoreDetails, PlayerDetails playerDetails, Date matchDate,
			int score, int bonus, int totalScore) {
		this.matchScoreDetails = matchScoreDetails;
		this.playerDetails = playerDetails;
		this.matchDate = matchDate;
		this.score = score;
		this.bonus = bonus;
		this.totalScore = totalScore;
	}

	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	public MatchScoreDetails getMatchScoreDetails() {
		return this.matchScoreDetails;
	}

	public void setMatchScoreDetails(MatchScoreDetails matchScoreDetails) {
		this.matchScoreDetails = matchScoreDetails;
	}

	public PlayerDetails getPlayerDetails() {
		return this.playerDetails;
	}

	public void setPlayerDetails(PlayerDetails playerDetails) {
		this.playerDetails = playerDetails;
	}

	public Date getMatchDate() {
		return this.matchDate;
	}

	public void setMatchDate(Date matchDate) {
		this.matchDate = matchDate;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public int getBonus() {
		return this.bonus;
	}

	public void setBonus(int bonus) {
		this.bonus = bonus;
	}

	public int getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(int totalScore) {
		this.totalScore = totalScore;
	}

}
