package com.adk.db.pingpong;
// Generated Dec 5, 2016 11:24:39 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * PlayerDetails generated by hbm2java
 */
@XmlRootElement 
public class PlayerDetails implements java.io.Serializable {

	private Integer playerId;
	private String playerName;
	private String fatherName;
	private String motherName;
	private String occupation;
	private Date dob;
	private Date dateOfJoining;
	private String mobileNumber;
	private String address;
	private int age;
	private boolean isParentPlayer;
	private boolean isParentWillingToLearn;
	private boolean isParentRefere;
	private String playerCode;
	private Set gameScoresForPlayer2Id = new HashSet(0);
	private Set scoreCards = new HashSet(0);
	private Set gameScoresForPlayer1Id = new HashSet(0);

	public PlayerDetails() {
	}

	public PlayerDetails(String playerName, String fatherName, String motherName, String occupation, Date dob,
			Date dateOfJoining, String mobileNumber, String address, int age, boolean isParentPlayer,
			boolean isParentWillingToLearn, boolean isParentRefere) {
		this.playerName = playerName;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.occupation = occupation;
		this.dob = dob;
		this.dateOfJoining = dateOfJoining;
		this.mobileNumber = mobileNumber;
		this.address = address;
		this.age = age;
		this.isParentPlayer = isParentPlayer;
		this.isParentWillingToLearn = isParentWillingToLearn;
		this.isParentRefere = isParentRefere;
	}

	public PlayerDetails(String playerName, String fatherName, String motherName, String occupation, Date dob,
			Date dateOfJoining, String mobileNumber, String address, int age, boolean isParentPlayer,
			boolean isParentWillingToLearn, boolean isParentRefere, String playerCode, Set gameScoresForPlayer2Id,
			Set scoreCards, Set gameScoresForPlayer1Id) {
		this.playerName = playerName;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.occupation = occupation;
		this.dob = dob;
		this.dateOfJoining = dateOfJoining;
		this.mobileNumber = mobileNumber;
		this.address = address;
		this.age = age;
		this.isParentPlayer = isParentPlayer;
		this.isParentWillingToLearn = isParentWillingToLearn;
		this.isParentRefere = isParentRefere;
		this.playerCode = playerCode;
		this.gameScoresForPlayer2Id = gameScoresForPlayer2Id;
		this.scoreCards = scoreCards;
		this.gameScoresForPlayer1Id = gameScoresForPlayer1Id;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public String getPlayerName() {
		return this.playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Date getDateOfJoining() {
		return this.dateOfJoining;
	}

	public void setDateOfJoining(Date dateOfJoining) {
		this.dateOfJoining = dateOfJoining;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public boolean isIsParentPlayer() {
		return this.isParentPlayer;
	}

	public void setIsParentPlayer(boolean isParentPlayer) {
		this.isParentPlayer = isParentPlayer;
	}

	public boolean isIsParentWillingToLearn() {
		return this.isParentWillingToLearn;
	}

	public void setIsParentWillingToLearn(boolean isParentWillingToLearn) {
		this.isParentWillingToLearn = isParentWillingToLearn;
	}

	public boolean isIsParentRefere() {
		return this.isParentRefere;
	}

	public void setIsParentRefere(boolean isParentRefere) {
		this.isParentRefere = isParentRefere;
	}

	public String getPlayerCode() {
		return this.playerCode;
	}

	public void setPlayerCode(String playerCode) {
		this.playerCode = playerCode;
	}

	public Set getGameScoresForPlayer2Id() {
		return this.gameScoresForPlayer2Id;
	}

	public void setGameScoresForPlayer2Id(Set gameScoresForPlayer2Id) {
		this.gameScoresForPlayer2Id = gameScoresForPlayer2Id;
	}

	public Set getScoreCards() {
		return this.scoreCards;
	}

	public void setScoreCards(Set scoreCards) {
		this.scoreCards = scoreCards;
	}

	public Set getGameScoresForPlayer1Id() {
		return this.gameScoresForPlayer1Id;
	}

	public void setGameScoresForPlayer1Id(Set gameScoresForPlayer1Id) {
		this.gameScoresForPlayer1Id = gameScoresForPlayer1Id;
	}

}
