package com.adk.db.pingpong;
// Generated Dec 5, 2016 10:30:31 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ScoreCard generated by hbm2java
 */
@XmlRootElement(name="scorecard") 
public class ScoreCard implements java.io.Serializable {

	private Integer scoreId;
	@XmlTransient
	private PlayerDetails playerDetails;
	private int totalScore;

	public ScoreCard() {
	}

	public ScoreCard(GameScore gameScore, PlayerDetails playerDetails, int totalScore) {
		
		this.playerDetails = playerDetails;
		this.totalScore = totalScore;
	}

	public Integer getScoreId() {
		return this.scoreId;
	}

	public void setScoreId(Integer scoreId) {
		this.scoreId = scoreId;
	}

	public PlayerDetails getPlayerDetails() {
		return this.playerDetails;
	}

	public void setPlayerDetails(PlayerDetails playerDetails) {
		this.playerDetails = playerDetails;
	}

	public int getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(int totalScore) {
		this.totalScore = totalScore;
	}

}
