package com.adk.db.pingpong;
// Generated Dec 24, 2016 8:57:25 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String username;
	private String password;
	private boolean enabled;
	private Set authoritieses = new HashSet(0);

	public Users() {
	}

	public Users(String username, String password, boolean enabled) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
	}

	public Users(String username, String password, boolean enabled, Set authoritieses) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.authoritieses = authoritieses;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set getAuthoritieses() {
		return this.authoritieses;
	}

	public void setAuthoritieses(Set authoritieses) {
		this.authoritieses = authoritieses;
	}

}
