package com.adk.db;
// Generated Nov 28, 2016 3:47:06 PM by Hibernate Tools 5.1.0.Alpha1
import javax.xml.bind.annotation.XmlRootElement;
/**
 * Person generated by hbm2java
 */
@XmlRootElement  
public class Person implements java.io.Serializable {

	private int id;
	private String name;
	private Integer age;

	public Person() {
	}

	public Person(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Person(int id, String name, Integer age) {
		this.id = id;
		this.name = name;
		this.age = age;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

}
